import type { 
  Course, 
  ScheduledClass, 
  Quiz, 
  HomeworkDeck,
  StudentProgress,
  Assessment,
  AssessmentAttempt,
  Question,
  GapTopic,
  AssessmentHistoryItem
} from '@/types';

// Helper to create dates relative to now
const today = new Date();
const addDays = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date;
};
const addHours = (hours: number) => {
  const date = new Date(today);
  date.setHours(date.getHours() + hours);
  return date;
};

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Calculus I',
    description: 'Introduction to differential and integral calculus. Covers limits, derivatives, and integrals of single-variable functions.',
    instructor: 'Dr. Sarah Chen',
    thumbnail: '/placeholder.svg',
    color: '#6366f1',
    progress: 68,
    totalClasses: 24,
    completedClasses: 16,
    concepts: [
      { id: 'c1-1', name: 'Limits', description: 'Understanding limits and continuity', masteryLevel: 85 },
      { id: 'c1-2', name: 'Derivatives', description: 'Rate of change and differentiation rules', masteryLevel: 72 },
      { id: 'c1-3', name: 'Chain Rule', description: 'Differentiation of composite functions', masteryLevel: 65 },
      { id: 'c1-4', name: 'Integration', description: 'Antiderivatives and definite integrals', masteryLevel: 45 },
    ],
  },
  {
    id: 'course-2',
    title: 'Physics: Mechanics',
    description: 'Classical mechanics covering motion, forces, energy, and momentum. Problem-solving focused approach.',
    instructor: 'Prof. James Miller',
    thumbnail: '/placeholder.svg',
    color: '#f59e0b',
    progress: 45,
    totalClasses: 20,
    completedClasses: 9,
    concepts: [
      { id: 'c2-1', name: 'Kinematics', description: 'Motion in one and two dimensions', masteryLevel: 78 },
      { id: 'c2-2', name: 'Newton\'s Laws', description: 'Forces and motion relationships', masteryLevel: 62 },
      { id: 'c2-3', name: 'Work & Energy', description: 'Energy conservation and transfer', masteryLevel: 55 },
      { id: 'c2-4', name: 'Momentum', description: 'Linear momentum and collisions', masteryLevel: 40 },
    ],
  },
  {
    id: 'course-3',
    title: 'Data Structures',
    description: 'Fundamental data structures and algorithms. Arrays, linked lists, trees, graphs, and sorting algorithms.',
    instructor: 'Dr. Emily Park',
    thumbnail: '/placeholder.svg',
    color: '#10b981',
    progress: 82,
    totalClasses: 18,
    completedClasses: 15,
    concepts: [
      { id: 'c3-1', name: 'Arrays & Lists', description: 'Linear data structures', masteryLevel: 92 },
      { id: 'c3-2', name: 'Trees', description: 'Binary trees and BST operations', masteryLevel: 85 },
      { id: 'c3-3', name: 'Graphs', description: 'Graph representations and traversals', masteryLevel: 70 },
      { id: 'c3-4', name: 'Sorting', description: 'Sorting algorithms and complexity', masteryLevel: 88 },
    ],
  },
];

export const mockSchedule: ScheduledClass[] = [
  {
    id: 'class-1',
    courseId: 'course-1',
    courseName: 'Calculus I',
    title: 'Integration by Parts',
    description: 'Learn the integration by parts technique for integrating products of functions.',
    startTime: addHours(-2),
    endTime: addHours(-1),
    status: 'completed',
    quizAvailable: true,
    content: {
      id: 'content-1',
      topics: ['Integration by Parts Formula', 'LIATE Rule', 'Tabular Method'],
      materials: [
        { id: 'm1', title: 'Lecture Slides', type: 'pdf', url: '#' },
        { id: 'm2', title: 'Practice Problems', type: 'pdf', url: '#' },
      ],
      notes: 'Integration by parts is derived from the product rule of differentiation.',
    },
  },
  {
    id: 'class-2',
    courseId: 'course-2',
    courseName: 'Physics: Mechanics',
    title: 'Conservation of Momentum',
    description: 'Understanding momentum conservation in isolated systems and collision analysis.',
    startTime: addHours(2),
    endTime: addHours(3),
    status: 'upcoming',
    quizAvailable: false,
    content: {
      id: 'content-2',
      topics: ['Momentum Definition', 'Impulse', 'Elastic & Inelastic Collisions'],
      materials: [
        { id: 'm3', title: 'Pre-class Reading', type: 'pdf', url: '#' },
      ],
      notes: '',
    },
  },
  {
    id: 'class-3',
    courseId: 'course-3',
    courseName: 'Data Structures',
    title: 'Graph Algorithms: BFS & DFS',
    description: 'Breadth-first and depth-first search algorithms with applications.',
    startTime: addDays(1),
    endTime: addDays(1),
    status: 'upcoming',
    quizAvailable: false,
    content: {
      id: 'content-3',
      topics: ['BFS Algorithm', 'DFS Algorithm', 'Applications'],
      materials: [],
      notes: '',
    },
  },
  {
    id: 'class-4',
    courseId: 'course-1',
    courseName: 'Calculus I',
    title: 'Trigonometric Integrals',
    description: 'Techniques for integrating trigonometric functions.',
    startTime: addDays(2),
    endTime: addDays(2),
    status: 'upcoming',
    quizAvailable: false,
  },
];

// Question bank for different topics
const questionBank: Question[] = [
  // Calculus - Limits
  {
    id: 'qb-1',
    text: 'What is the limit of (x² - 1)/(x - 1) as x approaches 1?',
    type: 'mcq',
    options: ['0', '1', '2', 'Does not exist'],
    correctAnswer: 2,
    explanation: 'Factor the numerator: (x+1)(x-1)/(x-1) = x+1. As x→1, the limit is 2.',
    conceptId: 'c1-1',
    conceptName: 'Limits',
    difficulty: 'easy',
    points: 10,
    topic: 'Limits'
  },
  {
    id: 'qb-2',
    text: 'Evaluate lim(x→∞) (3x² + 2x)/(x² - 1)',
    type: 'mcq',
    options: ['0', '1', '3', '∞'],
    correctAnswer: 2,
    explanation: 'Divide numerator and denominator by x². As x→∞, lower order terms vanish, leaving 3/1 = 3.',
    conceptId: 'c1-1',
    conceptName: 'Limits',
    difficulty: 'medium',
    points: 15,
    topic: 'Limits'
  },
  // Calculus - Derivatives
  {
    id: 'qb-3',
    text: 'What is the derivative of f(x) = x³ + 2x² - 5x + 1?',
    type: 'mcq',
    options: ['3x² + 4x - 5', '3x² + 2x - 5', 'x² + 2x - 5', '3x² + 4x'],
    correctAnswer: 0,
    explanation: 'Using power rule: d/dx(xⁿ) = nxⁿ⁻¹. So f\'(x) = 3x² + 4x - 5.',
    conceptId: 'c1-2',
    conceptName: 'Derivatives',
    difficulty: 'easy',
    points: 10,
    topic: 'Derivatives'
  },
  {
    id: 'qb-4',
    text: 'Find the derivative of y = sin(x²)',
    type: 'mcq',
    options: ['cos(x²)', '2x·cos(x²)', 'x·cos(x²)', '2·cos(x²)'],
    correctAnswer: 1,
    explanation: 'Using chain rule: dy/dx = cos(x²) · 2x = 2x·cos(x²)',
    conceptId: 'c1-3',
    conceptName: 'Chain Rule',
    difficulty: 'medium',
    points: 15,
    topic: 'Chain Rule'
  },
  // Calculus - Integration
  {
    id: 'qb-5',
    text: 'What is ∫2x dx?',
    type: 'mcq',
    options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
    correctAnswer: 0,
    explanation: 'Using power rule for integration: ∫2x dx = 2·(x²/2) + C = x² + C',
    conceptId: 'c1-4',
    conceptName: 'Integration',
    difficulty: 'easy',
    points: 10,
    topic: 'Integration'
  },
  {
    id: 'qb-6',
    text: 'Evaluate ∫eˣ·sin(x) dx requires which technique?',
    type: 'mcq',
    options: ['Substitution', 'Integration by parts (twice)', 'Partial fractions', 'Direct integration'],
    correctAnswer: 1,
    explanation: 'This integral requires applying integration by parts twice, then solving the resulting equation.',
    conceptId: 'c1-4',
    conceptName: 'Integration',
    difficulty: 'hard',
    points: 20,
    topic: 'Integration'
  },
  // Physics - Kinematics
  {
    id: 'qb-7',
    text: 'A car accelerates from rest at 2 m/s². What is its velocity after 5 seconds?',
    type: 'mcq',
    options: ['5 m/s', '10 m/s', '15 m/s', '25 m/s'],
    correctAnswer: 1,
    explanation: 'Using v = u + at: v = 0 + (2)(5) = 10 m/s',
    conceptId: 'c2-1',
    conceptName: 'Kinematics',
    difficulty: 'easy',
    points: 10,
    topic: 'Kinematics'
  },
  {
    id: 'qb-8',
    text: 'A ball is thrown upward with initial velocity 20 m/s. Maximum height reached is: (g=10 m/s²)',
    type: 'mcq',
    options: ['10 m', '20 m', '30 m', '40 m'],
    correctAnswer: 1,
    explanation: 'Using v² = u² - 2gh, at max height v=0: 0 = 400 - 20h, h = 20 m',
    conceptId: 'c2-1',
    conceptName: 'Kinematics',
    difficulty: 'medium',
    points: 15,
    topic: 'Kinematics'
  },
  // Physics - Newton's Laws
  {
    id: 'qb-9',
    text: 'According to Newton\'s third law, when you push against a wall:',
    type: 'mcq',
    options: [
      'The wall pushes back with less force',
      'The wall pushes back with equal force',
      'The wall doesn\'t push back',
      'The force disappears'
    ],
    correctAnswer: 1,
    explanation: 'Newton\'s third law states every action has an equal and opposite reaction.',
    conceptId: 'c2-2',
    conceptName: 'Newton\'s Laws',
    difficulty: 'easy',
    points: 10,
    topic: 'Newton\'s Laws'
  },
  {
    id: 'qb-10',
    text: 'A 5 kg object experiences a net force of 15 N. Its acceleration is:',
    type: 'mcq',
    options: ['1 m/s²', '2 m/s²', '3 m/s²', '5 m/s²'],
    correctAnswer: 2,
    explanation: 'Using F = ma: 15 = 5a, so a = 3 m/s²',
    conceptId: 'c2-2',
    conceptName: 'Newton\'s Laws',
    difficulty: 'easy',
    points: 10,
    topic: 'Newton\'s Laws'
  },
  // Data Structures - Arrays
  {
    id: 'qb-11',
    text: 'What is the time complexity of accessing an element in an array by index?',
    type: 'mcq',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    correctAnswer: 0,
    explanation: 'Array access by index is O(1) because arrays allow direct memory access.',
    conceptId: 'c3-1',
    conceptName: 'Arrays & Lists',
    difficulty: 'easy',
    points: 10,
    topic: 'Arrays'
  },
  {
    id: 'qb-12',
    text: 'Inserting at the beginning of a linked list has time complexity:',
    type: 'mcq',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    correctAnswer: 0,
    explanation: 'Inserting at head of linked list is O(1) - just update the head pointer.',
    conceptId: 'c3-1',
    conceptName: 'Arrays & Lists',
    difficulty: 'medium',
    points: 15,
    topic: 'Linked Lists'
  },
  // Data Structures - Trees
  {
    id: 'qb-13',
    text: 'In a Binary Search Tree, searching for an element has average time complexity:',
    type: 'mcq',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
    correctAnswer: 2,
    explanation: 'BST search is O(log n) on average as each comparison eliminates half the tree.',
    conceptId: 'c3-2',
    conceptName: 'Trees',
    difficulty: 'medium',
    points: 15,
    topic: 'Binary Search Trees'
  },
  {
    id: 'qb-14',
    text: 'The height of a balanced binary tree with n nodes is approximately:',
    type: 'mcq',
    options: ['n', 'n/2', 'log₂(n)', '√n'],
    correctAnswer: 2,
    explanation: 'A balanced binary tree has height O(log n) since nodes double at each level.',
    conceptId: 'c3-2',
    conceptName: 'Trees',
    difficulty: 'medium',
    points: 15,
    topic: 'Trees'
  },
  // Data Structures - Graphs
  {
    id: 'qb-15',
    text: 'BFS uses which data structure for traversal?',
    type: 'mcq',
    options: ['Stack', 'Queue', 'Heap', 'Tree'],
    correctAnswer: 1,
    explanation: 'BFS uses a queue to process nodes level by level in FIFO order.',
    conceptId: 'c3-3',
    conceptName: 'Graphs',
    difficulty: 'easy',
    points: 10,
    topic: 'Graph Traversal'
  },
  {
    id: 'qb-16',
    text: 'DFS can be implemented using:',
    type: 'mcq',
    options: ['Only recursion', 'Only stack', 'Either recursion or stack', 'Queue'],
    correctAnswer: 2,
    explanation: 'DFS can use recursion (implicit stack) or an explicit stack data structure.',
    conceptId: 'c3-3',
    conceptName: 'Graphs',
    difficulty: 'medium',
    points: 15,
    topic: 'Graph Traversal'
  },
];

export { questionBank };

export const mockQuiz: Quiz = {
  id: 'quiz-1',
  classId: 'class-1',
  courseId: 'course-1',
  title: 'Integration by Parts Quiz',
  description: 'Test your understanding of the integration by parts technique.',
  timeLimit: 15,
  createdAt: new Date(),
  questions: [
    {
      id: 'q1',
      text: 'What is the formula for integration by parts?',
      type: 'mcq',
      options: [
        '∫u dv = uv - ∫v du',
        '∫u dv = uv + ∫v du',
        '∫u dv = u + v - ∫du dv',
        '∫u dv = ∫u du + ∫v dv',
      ],
      correctAnswer: 0,
      explanation: 'The integration by parts formula ∫u dv = uv - ∫v du is derived from the product rule of differentiation: d(uv) = u dv + v du.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'easy',
      points: 10,
    },
    {
      id: 'q2',
      text: 'In LIATE rule, which function type should typically be chosen as "u"?',
      type: 'mcq',
      options: [
        'Exponential functions',
        'Trigonometric functions',
        'Logarithmic functions',
        'Algebraic functions',
      ],
      correctAnswer: 2,
      explanation: 'LIATE stands for Logarithmic, Inverse trig, Algebraic, Trigonometric, Exponential. Functions earlier in this list should be chosen as "u" because they become simpler when differentiated.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'medium',
      points: 15,
    },
    {
      id: 'q3',
      text: 'To integrate ∫x·eˣ dx, what should be chosen as u?',
      type: 'mcq',
      options: [
        'eˣ',
        'x',
        'x·eˣ',
        'dx',
      ],
      correctAnswer: 1,
      explanation: 'Using LIATE, x (algebraic) comes before eˣ (exponential), so u = x. This gives du = dx and dv = eˣ dx, making the integral simpler.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'medium',
      points: 15,
    },
    {
      id: 'q4',
      text: 'What is the result of ∫ln(x) dx?',
      type: 'mcq',
      options: [
        'x·ln(x) + x + C',
        'x·ln(x) - x + C',
        '1/x + C',
        'x/ln(x) + C',
      ],
      correctAnswer: 1,
      explanation: 'Using integration by parts with u = ln(x) and dv = dx: ∫ln(x) dx = x·ln(x) - ∫x·(1/x) dx = x·ln(x) - x + C',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'hard',
      points: 20,
    },
    {
      id: 'q5',
      text: 'Integration by parts may need to be applied multiple times for some integrals.',
      type: 'true-false',
      options: ['True', 'False'],
      correctAnswer: 0,
      explanation: 'True! For integrals like ∫x²·eˣ dx, you need to apply integration by parts twice. The tabular method can help organize repeated applications.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'easy',
      points: 10,
    },
  ],
};

// Mock Assessments
export const mockAssessments: Assessment[] = [
  {
    id: 'practice-1',
    type: 'practice',
    title: 'Calculus Practice',
    description: 'Practice problems on limits, derivatives, and integration',
    courseId: 'course-1',
    courseName: 'Calculus I',
    topics: ['Limits', 'Derivatives', 'Integration'],
    questions: questionBank.filter(q => ['c1-1', 'c1-2', 'c1-3', 'c1-4'].includes(q.conceptId)),
    totalQuestions: 6,
    status: 'available',
    createdAt: new Date(),
    difficulty: 'mixed',
    estimatedTime: 15,
  },
  {
    id: 'practice-2',
    type: 'practice',
    title: 'Physics Practice',
    description: 'Practice problems on mechanics fundamentals',
    courseId: 'course-2',
    courseName: 'Physics: Mechanics',
    topics: ['Kinematics', 'Newton\'s Laws'],
    questions: questionBank.filter(q => ['c2-1', 'c2-2'].includes(q.conceptId)),
    totalQuestions: 4,
    status: 'available',
    createdAt: new Date(),
    difficulty: 'mixed',
    estimatedTime: 10,
  },
  {
    id: 'mock-1',
    type: 'mock',
    title: 'Weekly Mock Test',
    description: 'Comprehensive exam simulation covering all subjects',
    topics: ['All Topics'],
    questions: questionBank,
    timeLimit: 30,
    totalQuestions: 16,
    status: 'scheduled',
    scheduledAt: addDays(2),
    createdAt: new Date(),
    difficulty: 'mixed',
    estimatedTime: 30,
  },
  {
    id: 'progress-1',
    type: 'progress',
    title: 'Progress Check: Calculus',
    description: 'Bi-weekly assessment to track your calculus learning',
    courseId: 'course-1',
    courseName: 'Calculus I',
    topics: ['Limits', 'Derivatives', 'Chain Rule', 'Integration'],
    questions: questionBank.filter(q => ['c1-1', 'c1-2', 'c1-3', 'c1-4'].includes(q.conceptId)),
    totalQuestions: 6,
    status: 'available',
    createdAt: new Date(),
    difficulty: 'medium',
    estimatedTime: 20,
  },
  {
    id: 'gap-1',
    type: 'gap',
    title: 'Gap Analysis: Integration',
    description: 'Targeted practice for your weak areas in integration',
    courseId: 'course-1',
    courseName: 'Calculus I',
    topics: ['Integration'],
    questions: questionBank.filter(q => q.conceptId === 'c1-4'),
    totalQuestions: 2,
    status: 'available',
    createdAt: new Date(),
    difficulty: 'hard',
    estimatedTime: 10,
  },
  {
    id: 'gap-2',
    type: 'gap',
    title: 'Gap Analysis: Momentum',
    description: 'Focus on momentum concepts where you need improvement',
    courseId: 'course-2',
    courseName: 'Physics: Mechanics',
    topics: ['Momentum'],
    questions: questionBank.filter(q => q.conceptId === 'c2-4' || q.topic === 'Momentum'),
    totalQuestions: 2,
    status: 'available',
    createdAt: new Date(),
    difficulty: 'medium',
    estimatedTime: 8,
  },
];

export const mockHomeworkDeck: HomeworkDeck = {
  id: 'hw-1',
  courseId: 'course-1',
  classId: 'class-1',
  title: 'Integration Practice Set',
  description: 'Practice problems based on today\'s class and previous topics.',
  dueAt: addDays(3),
  status: 'pending',
  progress: 0,
  questions: [
    // Current mistakes (50%)
    ...Array.from({ length: 10 }, (_, i) => ({
      id: `hw-q-${i + 1}`,
      text: `Practice Problem ${i + 1}: Apply integration by parts to solve the following integral.`,
      type: 'short-answer' as const,
      correctAnswer: 'Solution varies',
      explanation: 'Step-by-step solution would be provided here.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'medium' as const,
      points: 5,
      category: 'current-mistakes' as const,
      isCompleted: false,
      attempts: 0,
    })),
    // Past mistakes (30%)
    ...Array.from({ length: 6 }, (_, i) => ({
      id: `hw-q-${i + 11}`,
      text: `Review Problem ${i + 1}: Derivatives and chain rule practice.`,
      type: 'short-answer' as const,
      correctAnswer: 'Solution varies',
      explanation: 'Review of previously learned concepts.',
      conceptId: 'c1-3',
      conceptName: 'Chain Rule',
      difficulty: 'medium' as const,
      points: 5,
      category: 'past-mistakes' as const,
      isCompleted: false,
      attempts: 0,
    })),
    // New concepts (20%)
    ...Array.from({ length: 4 }, (_, i) => ({
      id: `hw-q-${i + 17}`,
      text: `New Concept ${i + 1}: Additional integration technique practice.`,
      type: 'short-answer' as const,
      correctAnswer: 'Solution varies',
      explanation: 'Exploring new integration methods.',
      conceptId: 'c1-4',
      conceptName: 'Integration',
      difficulty: 'hard' as const,
      points: 10,
      category: 'new-concepts' as const,
      isCompleted: false,
      attempts: 0,
    })),
  ],
};

export const mockGapTopics: GapTopic[] = [
  {
    conceptId: 'c1-4',
    conceptName: 'Integration',
    topic: 'Integration by Parts',
    accuracy: 45,
    questionsAttempted: 12,
    lastAttempted: addDays(-1),
  },
  {
    conceptId: 'c2-4',
    conceptName: 'Momentum',
    topic: 'Collision Analysis',
    accuracy: 40,
    questionsAttempted: 8,
    lastAttempted: addDays(-3),
  },
  {
    conceptId: 'c1-3',
    conceptName: 'Chain Rule',
    topic: 'Nested Functions',
    accuracy: 55,
    questionsAttempted: 15,
    lastAttempted: addDays(-2),
  },
];

export const mockAssessmentHistory: AssessmentHistoryItem[] = [
  {
    id: 'hist-1',
    type: 'class-quiz',
    title: 'Integration by Parts Quiz',
    score: 65,
    totalPoints: 100,
    percentage: 65,
    completedAt: addDays(-1),
    timeSpent: 720,
  },
  {
    id: 'hist-2',
    type: 'practice',
    title: 'Derivatives Practice',
    score: 85,
    totalPoints: 100,
    percentage: 85,
    completedAt: addDays(-3),
    timeSpent: 540,
  },
  {
    id: 'hist-3',
    type: 'progress',
    title: 'Weekly Progress Test',
    score: 72,
    totalPoints: 100,
    percentage: 72,
    completedAt: addDays(-7),
    timeSpent: 1200,
  },
  {
    id: 'hist-4',
    type: 'mock',
    title: 'Full Mock Exam',
    score: 68,
    totalPoints: 100,
    percentage: 68,
    completedAt: addDays(-14),
    timeSpent: 1800,
  },
];

export const mockProgress: StudentProgress = {
  userId: '1',
  courseId: 'course-1',
  overallMastery: 67,
  conceptMastery: {
    'c1-1': 85,
    'c1-2': 72,
    'c1-3': 65,
    'c1-4': 45,
    'c2-1': 78,
    'c2-2': 62,
    'c2-3': 55,
    'c2-4': 40,
    'c3-1': 92,
    'c3-2': 85,
    'c3-3': 70,
    'c3-4': 88,
  },
  quizScores: [
    { quizId: 'quiz-prev-1', score: 85, totalPoints: 100, completedAt: addDays(-7) },
    { quizId: 'quiz-prev-2', score: 72, totalPoints: 100, completedAt: addDays(-5) },
    { quizId: 'quiz-prev-3', score: 68, totalPoints: 100, completedAt: addDays(-3) },
  ],
  homeworkCompletion: 78,
  streakDays: 5,
  totalTimeSpent: 1847, // minutes
  weakAreas: ['Integration', 'Momentum', 'Chain Rule'],
  strongAreas: ['Limits', 'Arrays & Lists', 'Sorting'],
  assessmentHistory: mockAssessmentHistory,
  gapTopics: mockGapTopics,
};
