import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppLayout } from '@/components/layout/AppLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { api } from '@/services/api';
import type { AIAssessment, AIAssessmentsResponse } from '@/types';
import { 
  FileText, 
  Clock, 
  Target, 
  BookOpen,
  Play,
  Loader2,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Calendar
} from 'lucide-react';
import { cn } from '@/lib/utils';

const difficultyColors = {
  easy: 'bg-green-500/10 text-green-500 border-green-500/20',
  medium: 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20',
  hard: 'bg-red-500/10 text-red-500 border-red-500/20',
};

const statusConfig = {
  completed: { icon: CheckCircle2, color: 'text-green-500', label: 'Completed' },
  failed: { icon: XCircle, color: 'text-red-500', label: 'Failed' },
  pending: { icon: Loader2, color: 'text-yellow-500', label: 'Pending' },
};

export default function TestsPage() {
  const navigate = useNavigate();
  const [assessments, setAssessments] = useState<AIAssessment[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'completed' | 'failed'>('all');

  useEffect(() => {
    loadAssessments();
  }, []);

  const loadAssessments = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const response: AIAssessmentsResponse = await api.getTeacherAssessments(50, 0);
      setAssessments(response.assessments);
    } catch (err) {
      setError('Failed to load assessments. Please try again later.');
      console.error('Error loading assessments:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const filteredAssessments = assessments.filter(assessment => {
    if (filter === 'all') return true;
    return assessment.status === filter;
  });

  const completedCount = assessments.filter(a => a.status === 'completed').length;
  const failedCount = assessments.filter(a => a.status === 'failed').length;

  const handleStartTest = (assessmentId: string) => {
    navigate(`/tests/${assessmentId}`);
  };

  return (
    <AppLayout>
      <div className="container mx-auto py-8 px-4 max-w-7xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">AI-Generated Tests</h1>
          <p className="text-muted-foreground">
            Tests generated by the AI assessment system from pupil-agents
          </p>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Total Tests</p>
                  <p className="text-2xl font-bold">{assessments.length}</p>
                </div>
                <FileText className="h-8 w-8 text-primary" />
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Completed</p>
                  <p className="text-2xl font-bold text-green-500">{completedCount}</p>
                </div>
                <CheckCircle2 className="h-8 w-8 text-green-500" />
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Failed</p>
                  <p className="text-2xl font-bold text-red-500">{failedCount}</p>
                </div>
                <XCircle className="h-8 w-8 text-red-500" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Filter Tabs */}
        <div className="flex gap-2 mb-6">
          <Button
            variant={filter === 'all' ? 'default' : 'outline'}
            onClick={() => setFilter('all')}
          >
            All Tests
          </Button>
          <Button
            variant={filter === 'completed' ? 'default' : 'outline'}
            onClick={() => setFilter('completed')}
          >
            Completed
          </Button>
          <Button
            variant={filter === 'failed' ? 'default' : 'outline'}
            onClick={() => setFilter('failed')}
          >
            Failed
          </Button>
        </div>

        {/* Loading State */}
        {isLoading && (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <span className="ml-2 text-lg">Loading assessments...</span>
          </div>
        )}

        {/* Error State */}
        {error && !isLoading && (
          <Card className="border-destructive">
            <CardContent className="pt-6">
              <div className="flex items-center gap-2 text-destructive">
                <AlertCircle className="h-5 w-5" />
                <p>{error}</p>
              </div>
              <Button onClick={loadAssessments} className="mt-4">
                Try Again
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Assessments Grid */}
        {!isLoading && !error && filteredAssessments.length === 0 && (
          <Card>
            <CardContent className="pt-6 text-center">
              <FileText className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
              <p className="text-lg text-muted-foreground">
                No assessments found for the selected filter
              </p>
            </CardContent>
          </Card>
        )}

        {!isLoading && !error && filteredAssessments.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredAssessments.map((assessment) => {
              const StatusIcon = statusConfig[assessment.status].icon;
              
              return (
                <Card 
                  key={assessment.id} 
                  className={cn(
                    "hover:shadow-lg transition-shadow cursor-pointer",
                    assessment.status === 'failed' && "opacity-60"
                  )}
                >
                  <CardHeader>
                    <div className="flex items-start justify-between mb-2">
                      <Badge 
                        variant="outline" 
                        className={cn(
                          "capitalize",
                          statusConfig[assessment.status].color
                        )}
                      >
                        <StatusIcon className={cn(
                          "h-3 w-3 mr-1",
                          assessment.status === 'pending' && "animate-spin"
                        )} />
                        {statusConfig[assessment.status].label}
                      </Badge>
                      {assessment.difficulty && (
                        <Badge 
                          variant="outline" 
                          className={difficultyColors[assessment.difficulty]}
                        >
                          {assessment.difficulty}
                        </Badge>
                      )}
                    </div>
                    <CardTitle className="text-lg line-clamp-2">
                      {assessment.test_name || 'Untitled Test'}
                    </CardTitle>
                    {assessment.subject && (
                      <CardDescription className="flex items-center gap-1">
                        <BookOpen className="h-4 w-4" />
                        {assessment.subject}
                      </CardDescription>
                    )}
                  </CardHeader>
                  
                  <CardContent>
                    <div className="space-y-3">
                      {/* Test Info */}
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-muted-foreground flex items-center gap-1">
                          <Target className="h-4 w-4" />
                          Questions
                        </span>
                        <span className="font-medium">
                          {assessment.number_of_questions || 'N/A'}
                        </span>
                      </div>

                      {assessment.estimated_time_minutes && (
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-muted-foreground flex items-center gap-1">
                            <Clock className="h-4 w-4" />
                            Duration
                          </span>
                          <span className="font-medium">
                            {assessment.estimated_time_minutes} min
                          </span>
                        </div>
                      )}

                      {assessment.total_marks && (
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-muted-foreground flex items-center gap-1">
                            <FileText className="h-4 w-4" />
                            Total Marks
                          </span>
                          <span className="font-medium">
                            {assessment.total_marks}
                          </span>
                        </div>
                      )}

                      {assessment.created_at && (
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-muted-foreground flex items-center gap-1">
                            <Calendar className="h-4 w-4" />
                            Created
                          </span>
                          <span className="font-medium">
                            {new Date(assessment.created_at).toLocaleDateString()}
                          </span>
                        </div>
                      )}

                      {/* Topics */}
                      {assessment.topics && assessment.topics.length > 0 && (
                        <div className="pt-2 border-t">
                          <p className="text-xs text-muted-foreground mb-2">Topics:</p>
                          <div className="flex flex-wrap gap-1">
                            {assessment.topics.slice(0, 3).map((topic, idx) => (
                              <Badge 
                                key={idx} 
                                variant="secondary" 
                                className="text-xs"
                              >
                                {topic}
                              </Badge>
                            ))}
                            {assessment.topics.length > 3 && (
                              <Badge variant="secondary" className="text-xs">
                                +{assessment.topics.length - 3} more
                              </Badge>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Action Button */}
                      {assessment.status === 'completed' && (
                        <Button 
                          className="w-full mt-4"
                          onClick={() => handleStartTest(assessment.id)}
                        >
                          <Play className="h-4 w-4 mr-2" />
                          Start Test
                        </Button>
                      )}

                      {assessment.status === 'failed' && (
                        <Button 
                          className="w-full mt-4"
                          variant="outline"
                          disabled
                        >
                          Test Generation Failed
                        </Button>
                      )}

                      {assessment.status === 'pending' && (
                        <Button 
                          className="w-full mt-4"
                          variant="outline"
                          disabled
                        >
                          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                          Generating...
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
